# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          commit_hash=$(git rev-parse HEAD | cut -c -7)
          build_time=$(date "+%Y-%m-%dT%H:%M:%S")
          
          echo "[vars]" >> wrangler.toml
          echo "COMMIT_HASH = $commit_hash" >> wrangler.toml
          echo "BUILD_TIME = $build_time" >> wrangler.toml
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm run build --if-present
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
